apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webusers.fullname" . }}
  labels:
    {{- include "webusers.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webusers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webusers.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webusers.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENV_NAME
              value: "DEVELOPMENT"          
            - name: MONGO_HOST
              value: "cluster0.tvmkw.mongodb.net"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_NAME
              value: "mdr-usersnest"
            - name: MONGO_PASSWORD
              value: "ramos111"
            - name: MONGO_USER
              value: "dbAdmin"
          ports:
            - name: http
              containerPort: 3022
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3007
          resources:
             {{- toYaml .Values.resources | nindent 12 }}
             {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
